#!/bin/sh
#by mr virus spm
#wah ada kang record 

blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'

clear
sleep 2
xdg-open https://youtube.com/channel/UCSJohuQCtqfD2P73Z65g8jg
echo 
sleep 2 
echo -e "+++++++++++++++++++++++++++++++++++++++++"
echo -e "AUTHOR: ROZAAN SR"
echo -e "KONTAK: 083820004524"
echo -e "+++++++++++++++++++++++++++++++++++++++++"
echo
echo
sleep 1
echo $purple" GUNAKAN TOOLS INI DENGAN BIJAK"
echo $cyan"°==============================°"
echo
         sleep 1
         echo $cyan"["$yellow"01"$cyan"]"$purple" CHEAT ML 1"
         echo $cyan"["$yellow"02"$cyan"]"$purple" CHEAT ML 2"
         echo $cyan"["$yellow"03"$cyan"]"$purple" KELUAR"
         echo
         sleep 1
echo $cyan":::::::::::::::::::::::"
echo $cyan"::"$yellow" MASUKAN PILIHANMU"$cyan" ::"
echo $cyan":::::::::::::::::::::::"
echo
sleep 1
read -p "=> " gady

if [ $gady = 1 ] || [ $gady = 01 ]
then
    sleep 1
    echo $red"SEDANG"$yellow" MENUJU"$green" KE"$blue" LINK"
    sleep 3
    https://www.mediafire.com/file/11ybjk5mx9l2caj/APK_MOD__PATCH_AULUS.7z/file
fi
if [ $gady = 2 ] || [ $gady = 02 ]
then
    sllep 1
    echo $red"SEDANG"$yellow" MENUJU"$green" KE"$blue" LINK"
    sleep 3
    https://www.mediafire.com/file/0he3dbcdzfs9gnz/MOD_CHEAT_BRUTAL.7z/file
fi
if [ $gady = 3 ] || [ $gady = 03 ]
then
    sleep 1
    echo $yellow"TERIMAKASIH TELAH MENGGUNAKAN SCRIPT SAYA INGAT DI FILE NYA ADA PASSWORD UNTUK PASSWORD HUBUNGI KONTAK DI ATAS"
    sleep 1
    echo $cyan"SALAM  ROZAAN SR"
        exit
fi
